git:
  depth: 1

services:
  - docker

before_install:
  - docker pull hyperiongray/agnostic-tests:latest
  - docker run -d --name agnostic-tests -v $TRAVIS_BUILD_DIR:/opt/agnostic hyperiongray/agnostic-tests
  - sleep 10 # Allow time for Docker container & databases to start up.

script:
  - docker exec agnostic-tests bash -c "cd /opt/agnostic && python3 -m tests --with-coverage --cover-package agnostic --with-reportclassname -v"

after_success:
  - docker exec -e TRAVIS=true -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" -e TRAVIS_PULL_REQUEST="$TRAVIS_PULL_REQUEST" agnostic-tests bash -c "cd /opt/agnostic && coveralls"

after_script:
  - docker stop agnostic-tests
